[package]
name = "wolf_engine"
description = "A simple, flexible game framework."
version = "0.26.0"
authors = ["AlexiWolf <alexi@wolvesin.space>"]
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/AlexiWolf/wolf_engine"
homepage = "https://github.com/AlexiWolf/wolf_engine"
keywords = ["wolf-engine", "gamedev"]
categories = ["game-development", "game-engines"]

[workspace]
members = ["crates/*"]

[dependencies]
wolf_engine_events = { version = "0.1.0", path = "crates/wolf_engine_events", optional = true }
wolf_engine_input = { version = "0.1.0", path = "crates/wolf_engine_input", optional = true }

[features]
default = ["events", "dynamic", "input"]
events = ["wolf_engine_events"]
input = ["wolf_engine_input"]
dynamic = ["wolf_engine_events?/dynamic"]
winit = ["wolf_engine_input/winit"]

[dev-dependencies]
winit = "0.29.14"

[[example]]
name = "input"
required-features = ["winit"]

