//! Provides an event system for the window crate.

use uuid::Uuid;
use wolf_engine_input::Input;

use crate::{error::WindowError, Window, WindowSettings};

/// An event generated by the window system.
#[derive(Clone, PartialEq, Debug)]
#[non_exhaustive]
pub enum Event {
    Started,
    EventsCleared,
    WindowEvent(Uuid, WindowEvent),
    Input(Input),
    Exited,
}

/// An event generated by a specific window.
#[derive(Clone, PartialEq, Debug)]
#[non_exhaustive]
pub enum WindowEvent {
    Ready(Result<(), WindowError>),
    RedrawRequested,
    Resized(u32, u32),
    Closed,
    Input(Input),
}

#[derive(Debug)]
pub enum BackendEvent {
    CreateWindow(Uuid, WindowSettings),
    WindowDropped(Uuid),
    WindowClosed(Uuid),
    Exit,
}
