//! Provides an event system for the window crate.

use uuid::Uuid;
use wolf_engine_input::Input;

use crate::{error::WindowError, WindowSettings};

type Size = (u32, u32);

/// An event generated by the window system.
#[derive(Clone, PartialEq, Debug)]
#[non_exhaustive]
pub enum WindowEvent {
    Started,
    Exited,
    EventsCleared,
    Input(Option<Uuid>, Input),

    WindowReady(Uuid, Result<(), WindowError>),
    WindowRedrawRequested(Uuid),
    WindowResized(Uuid, Size),
    WindowCloseRequested(Uuid),
}

#[derive(Debug)]
pub enum BackendEvent {
    CreateWindow(Uuid, WindowSettings),
    WindowDropped(Uuid),
    WindowClosed(Uuid),
    RedrawRequested(Uuid),
}
